title: Produk
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
          display: Nama
          instructions_position: above
          listable: hidden
          input_type: text
          antlers: false
      -
        handle: foto
        field:
          mode: list
          restrict: false
          allow_uploads: true
          show_filename: true
          max_files: 1
          display: Foto
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
      -
        handle: harga
        field:
          input_type: number
          antlers: false
          display: Harga
          type: text
          icon: text
          listable: hidden
          instructions_position: above
      -
        handle: deskripsi
        field:
          input_type: text
          antlers: false
          display: Deskripsi
          type: text
          icon: text
          listable: hidden
          instructions_position: above
      -
        handle: ukuran
        field:
          input_type: text
          antlers: false
          display: Ukuran
          type: text
          icon: text
          listable: hidden
          instructions_position: above
      -
        handle: unggulan
        field:
          options:
            ya: Ya
            tidak: Tidak
          inline: false
          cast_booleans: false
          default: tidak
          display: Unggulan
          type: radio
          icon: radio
          listable: hidden
          instructions_position: above
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
          validate:
            - required
      -
        handle: date
        field:
          type: date
          required: true
          validate:
            - required
      -
        handle: tags
        field:
          type: terms
          taxonomies:
            - tags
          display: Tags
          mode: select
